### ISSUE TITLE
ECONNREFUSED with CouchDb2 on HighSierra

### ISSUE THREAD

**Issue by wassx** [gesellix/couchdb-2-elasticsearch#3]
Hi!
Thank you for this VERY useful tool.
I tried to migrate my couchdb to elastic but when i run

` sudo docker run -e couch2elastic4sync_database=http://localhost:5984/jobs -e couch2elastic4sync_elasticsearch=http://localhost:9200/index/type -e couch2elastic4sync_mapper=drop_design_docs gesellix/river load`

the script crashes with:
```
> couch2elastic4sync load

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:5984
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)

npm ERR! Linux 4.9.49-moby
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "load"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! couchdb-2-elasticsearch@0.0.1 load: `couch2elastic4sync load`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the couchdb-2-elasticsearch@0.0.1 load script 'couch2elastic4sync load'.
```

CouchDb si reachable via curl or browser. Do you have an idea what could cause the issue please?

**Comment by gesellix** [comment]
When using Docker you cannot use `localhost` to connect to a service running on your host. I assume your CouchDB is running on the host (available via localhost:5984 _from that host_). So instead of `localhost` you should try the actual host ip or the hostname.
Please give it a try - depending on your environment this might work... or not ;-) If not, feel free to leave a note here and we'll try to solve it together.

**Comment by wassx** [comment]
Thanks for the reply! :) I solved it in the meanwhile with a own script. Thanks for the inspiration!
